"""Reality check: ``python -m app.audit_runtime`` (§35).

Prints whether Red and Blue are real model backends or mocks, the active models and
harness, and the persisted counters. Exits non-zero when a real run is requested but
a provider is missing or unreachable, so a mock run can never be mistaken for an
experiment.
"""

from __future__ import annotations

import asyncio
import sys

from app.coevolution.providers import ProviderConfig, ProviderError, probe
from app.coevolution.runtime import assert_real_run, build_stack
from app.config import Settings


async def main() -> int:
    settings = Settings()
    try:
        stack = await build_stack(settings)
    except ProviderError as exc:
        print(f"PROVIDER ERROR: {exc}", file=sys.stderr)
        return 1
    repository = stack.repository
    calls = await repository.list_model_calls(limit=5_000)
    red_calls = sum(1 for call in calls if call.role in {"red_attacker", "red_mutator"})
    blue_calls = sum(1 for call in calls if call.role in {"blue_executor", "blue_harness_engineer"})
    candidates = await repository.list_attack_candidates()
    patches = await repository.list_patch_records()
    harnesses = await repository.list_harnesses()
    active = await repository.get_active_harness()
    report = None
    if candidates:
        report = await repository.get_run_report(candidates[-1].run_id)

    if stack.is_mock:
        red_verdict = blue_verdict = "MOCK (TEST_MODE)"
    elif settings.effective_run_mode == "DEV":
        red_verdict = blue_verdict = "LIVE (DEV MODE)"
    else:
        red_verdict = "REAL"
        blue_verdict = "REAL"

    print("RUN MODE")
    print(settings.effective_run_mode)
    print("")
    print("RED PROVIDER")
    print(stack.red_provider.config.provider if stack.red_provider else "TEST_MODE deterministic")
    print(red_verdict)
    print("")
    print("BLUE PROVIDER")
    print(stack.blue_provider.config.provider if stack.blue_provider else "TEST_MODE deterministic")
    print(blue_verdict)
    print("")
    print("ACTIVE RED MODEL")
    print(stack.red_provider.model if stack.red_provider else "test-mode-deterministic")
    print("")
    print("ACTIVE BLUE MODEL")
    print(stack.blue_provider.model if stack.blue_provider else "test-mode-deterministic")
    print("")
    print("CURRENT BLUE HARNESS")
    if active is not None:
        print(f"{active.version.id} (status={active.version.status}, fitness={active.version.fitness})")
    else:
        print("none deployed yet")
    print("")
    print("TOTAL REAL RED MODEL CALLS")
    print(red_calls)
    print("")
    print("TOTAL REAL BLUE MODEL CALLS")
    print(blue_calls)
    print("")
    print("ATTACKS GENERATED BY RED")
    print(len(candidates))
    print("")
    print("HARNESS PATCHES GENERATED BY BLUE")
    print(sum(1 for patch in patches if not patch.id.endswith("-RESULT")))
    print("")
    print("CANDIDATES COMPILED")
    print(sum(1 for record in harnesses if record.deployment.compiled_at is not None))
    print("")
    print("CANDIDATES PROMOTED")
    print(sum(1 for record in harnesses if record.deployment.status == "PROMOTED"))
    print("")
    print("MONGODB")
    if repository.backend == "mongodb":
        print("connected")
    elif repository.backend == "dev_snapshot":
        print("DEV / ATLAS NOT CONNECTED (durable snapshot)")
        print("note: counters above survive restarts through the labelled DEV snapshot, not Atlas.")
    else:
        print("DEV / ATLAS NOT CONNECTED (in-memory)")
        print("note: counters above are process-local until a durable DEV adapter or Atlas is configured.")
    print("")
    print("VECTOR SEARCH")
    print(stack.vector_memory.observed_retrieval_backend)
    if report is not None:
        print("")
        print("LAST RUN")
        print(f"{report.run_id}: red={report.red_versions_created} blue={report.blue_versions_created} "
              f"attacks={report.attacks_generated} successful={report.attacks_successful} "
              f"patches={report.harness_patches_generated} promoted={report.candidates_promoted}")
    status = 0
    if settings.effective_run_mode == "REAL":
        try:
            await assert_real_run(stack)
        except ProviderError as exc:
            print(f"PROVIDER ERROR: {exc}", file=sys.stderr)
            status = 1
    elif not stack.is_mock:
        try:
            results = await asyncio.gather(probe(ProviderConfig.red(settings)), probe(ProviderConfig.blue(settings)))
        except ProviderError as exc:
            print("")
            print(f"PROVIDER ERROR: {exc}", file=sys.stderr)
            status = 1
        else:
            for result in results:
                if not result.reachable:
                    print(f"PROVIDER ERROR: {result.role_name}_PROVIDER_UNAVAILABLE: {result.detail}", file=sys.stderr)
                    status = 1
    await stack.close()
    return status


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
